name             'code_generator'
maintainer       'JJ Asghar'
maintainer_email 'jj@chef.io'
license          'Apache 2 License'
description      'Generates the a cookbook for jjs cookbooks'
long_description 'Generates the a cookbook for jjs cookbooks'
version          '1.0.0'

issues_url 'https://github.com/jjasghar/jj-cookbook-generator/issues'
source_url 'https://github.com/jjasghar/jj-cookbook-generator'
